### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by roland04** [wafaahamdy/Moodle-Bulkresetpassword#3]
In [lib.php:31](https://github.com/wafaahamdy/Moodle-Bulkresetpassword/blob/main/lib.php#L31)
Please see:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#function-names

Also taking lib.php recommendations into account (https://moodledev.io/docs/apis/commonfiles#libphp) another option could be to move `reset_password_sendmail` to a different class.

Note this is a blocker for plugins db approval

**Comment by danmarsden** [comment]
also this class is named incorrectly as well:
https://github.com/wafaahamdy/Moodle-Bulkresetpassword/blob/main/form.php#L33

ideally you'd put it into the classes folder in your code and put it in the plugin namespace.

**Comment by wafaahamdy** [comment]
Thanks for your valuable feedback

I created a new class to handle password reset and email process. I put this class under class folder
https://github.com/wafaahamdy/moodle-tool_resetpasswords/blob/approval_issues/classes/rest_sendmail.php

I created new class for for under class/form folder
https://github.com/wafaahamdy/moodle-tool_resetpasswords/blob/approval_issues/classes/form/uploadlistform.php
